### ISSUE TITLE
feat(authentication) Possibility to make use of SSO with GUI

### ISSUE THREAD

**Issue by miguelanruiz** [mariadb-corporation/MaxGui#3]
Hello MariaDB Team, 

I am currently deploying the GUI which is quite useful and helpful, however I am finding that there is no information regarding the SSO implementation, I don't know yet if it is possible to use Oauth or SAML to authenticate users within the tool.

Can you help me to answer this question?

**Comment by mariadb-ThienLy** [comment]
Hi, both Oauth and SAML are not supported, but we do support PAM authentication. https://mariadb.com/kb/en/mariadb-maxscale-2302-pam-authenticator/
By the way, this repository is an outdated version of the GUI. The GUI is now a part of MaxScale: https://github.com/mariadb-corporation/MaxScale/tree/23.02.2/maxgui
